"""MCP server generated by agentsmd-mcp-bridge.

Source: AGENTS.md
Generated: 2026-07-07 04:10 UTC

Do not edit by hand. Regenerate with:
    agentsmd-mcp-bridge generate-mcp AGENTS.md -o examples/generated_mcp_server.py
"""

from __future__ import annotations

import shlex
import subprocess

from mcp.server.fastmcp import FastMCP

mcp = FastMCP("example-web-service")

_TIMEOUT_SECONDS = 300


def _run(command: str) -> str:
    """Execute a fixed documented command and return its combined output."""
    args = shlex.split(command)
    try:
        proc = subprocess.run(
            args,
            capture_output=True,
            text=True,
            timeout=_TIMEOUT_SECONDS,
            check=False,
        )
    except FileNotFoundError:
        return f"error: executable not found for command: {command!r}"
    except subprocess.TimeoutExpired:
        return f"error: command timed out after {_TIMEOUT_SECONDS}s: {command!r}"
    out = (proc.stdout or "") + (proc.stderr or "")
    return f"exit_code={proc.returncode}\n{out}".rstrip()


@mcp.tool()
def setup() -> str:
    """Setup

    Runs: pip install -r requirements.txt
    """
    return _run('pip install -r requirements.txt')


@mcp.tool()
def build() -> str:
    """Build

    Runs: python3 -m build
    """
    return _run('python3 -m build')


@mcp.tool()
def test() -> str:
    """Test

    Runs: pytest -q
    """
    return _run('pytest -q')


@mcp.tool()
def lint() -> str:
    """Lint

    Runs: ruff check src
    """
    return _run('ruff check src')


if __name__ == "__main__":
    mcp.run()
