"""Generate a Model Context Protocol (MCP) server from extracted commands.

The generated server uses the official MCP Python SDK (FastMCP). Each documented
command becomes one MCP tool that executes the command with a timeout and
returns its combined output. For safety the generated tools:

  * run the fixed documented command only, with no caller-supplied arguments,
  * execute via a shell-free argument list (shlex.split), avoiding injection,
  * enforce a timeout and capture output rather than streaming to the host.
"""

from __future__ import annotations

import datetime as _dt

from .models import Command

_HEADER = '''"""MCP server generated by agentsmd-mcp-bridge.

Source: AGENTS.md
Generated: {ts}

Do not edit by hand. Regenerate with:
    agentsmd-mcp-bridge generate-mcp AGENTS.md -o {out}
"""

from __future__ import annotations

import shlex
import subprocess

from mcp.server.fastmcp import FastMCP

mcp = FastMCP("{server}")

_TIMEOUT_SECONDS = 300


def _run(command: str) -> str:
    """Execute a fixed documented command and return its combined output."""
    args = shlex.split(command)
    try:
        proc = subprocess.run(
            args,
            capture_output=True,
            text=True,
            timeout=_TIMEOUT_SECONDS,
            check=False,
        )
    except FileNotFoundError:
        return f"error: executable not found for command: {{command!r}}"
    except subprocess.TimeoutExpired:
        return f"error: command timed out after {{_TIMEOUT_SECONDS}}s: {{command!r}}"
    out = (proc.stdout or "") + (proc.stderr or "")
    return f"exit_code={{proc.returncode}}\\n{{out}}".rstrip()

'''

_TOOL = '''
@mcp.tool()
def {name}() -> str:
    """{description}

    Runs: {command}
    """
    return _run({command!r})

'''

_FOOTER = '''
if __name__ == "__main__":
    mcp.run()
'''


def generate_mcp_server(
    commands: list[Command],
    server_name: str = "agentsmd-bridge",
    out_path: str = "mcp_server.py",
) -> str:
    """Generate Python source for an MCP server exposing the given commands.

    Args:
        commands: The commands to expose, one MCP tool per command.
        server_name: The MCP server name advertised to hosts.
        out_path: The output path, referenced in the regenerate hint.

    Returns:
        A complete Python module as a string.

    Raises:
        ValueError: If no commands are supplied.
    """
    if not commands:
        raise ValueError("no commands to expose; nothing to generate")

    ts = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    parts = [_HEADER.format(ts=ts, server=server_name, out=out_path)]
    seen: set[str] = set()
    for cmd in commands:
        if cmd.name in seen:
            continue
        seen.add(cmd.name)
        desc = cmd.description.replace('"', "'")
        parts.append(_TOOL.format(name=cmd.name, description=desc, command=cmd.command))
    parts.append(_FOOTER)
    return "".join(parts)
